title: StrideBR Documentation
author: Bruno Evaristo Pinheiro
logo: /public/assets/img/Logo.png
description: StrideBR Ã© um web app para atletas.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal