title: StrideBR Documentation
author: Bruno Evaristo Pinheiro
logo: /public/assets/img/logos/stridebr-logo.png
description: StrideBR is a web app for athletes.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal